typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="$(dirname "$(dirname "$(which zsh)")")/share/zsh/$ZSH_VERSION/help"

eval "$(zoxide init zsh )"

source $(dirname "$(dirname "$(which zsh-autosuggestions)")")/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history)


# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git zoxide zsh-vi-mode F-Sy-H)
ZSH_CUSTOM="$HOME/.zsh-custom"

source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="${HOME}/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


source $HOME/.zsh-custom/my-custom/aliases.zsh

source $HOME/.zsh-custom/my-custom/zsh-vi-mode.sh
nix() {
  if [ "$1" = 'develop' ]; then
    shift
    command nix develop -c "$SHELL" "$@"
  else
    command nix "$@"
  fi
}



if [[ $TERM != "dumb" ]]; then
  eval "$(starship init zsh)"
fi
