typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/5rhyxvk6ics6yg4rbjfgbmakj4nzdw11-zsh-5.9/share/zsh/$ZSH_VERSION/help"

eval "$(/nix/store/nvjgkixpdbgcj4r1nkhn9ins6ajw7hg6-zoxide-0.9.8/bin/zoxide init zsh )"

source /nix/store/jmvpz39dfd4pa6cxz1i7a8xys6ynh10p-zsh-autosuggestions-0.7.1/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history)


# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git zoxide zsh-vi-mode)
ZSH_CUSTOM="$HOME/.zsh-custom"

source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="/home/testUser/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


source $HOME/.zsh-custom/my-custom/zsh-vi-mode.sh
nix() {
  if [ "$1" = 'develop' ]; then
    shift
    command nix develop -c "$SHELL" "$@"
  else
    command nix "$@"
  fi
}



if [[ $TERM != "dumb" ]]; then
  eval "$(/nix/store/5l246fxvpc56b3g0lys9dhmg90ppr9y1-starship-1.23.0/bin/starship init zsh)"
fi
