typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="$(dirname "$(dirname "$(which zsh)")")/share/zsh/$ZSH_VERSION/help"


ZSH_AUTOSUGGEST_STRATEGY=(history)


# oh-my-zsh extra settings for plugins
path=($HOME/.local/bin $path)
export PATH
export ZSH_CUSTOM="$HOME/.zsh-custom"

# oh-my-zsh configuration generated by NixOS
plugins=(git git-auto-fetch F-Sy-H zsh-vi-mode zsh-autosuggestions)


source $ZSH/oh-my-zsh.sh



# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="${HOME}/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

# Set shell options
set_opts=(
  HIST_FCNTL_LOCK HIST_EXPIRE_DUPS_FIRST HIST_IGNORE_DUPS HIST_IGNORE_SPACE
  SHARE_HISTORY NO_APPEND_HISTORY NO_EXTENDED_HISTORY NO_HIST_FIND_NO_DUPS
  NO_HIST_IGNORE_ALL_DUPS NO_HIST_SAVE_NO_DUPS
)
for opt in "${set_opts[@]}"; do
  setopt "$opt"
done
unset opt set_opts

source $HOME/.zsh-custom/my-custom/functions.zsh

source $HOME/.zsh-custom/my-custom/aliases.zsh

source $HOME/.zsh-custom/my-custom/zsh-vi-mode.sh
nix() {
  if [ "$1" = 'develop' ]; then
    shift
    command nix develop -c "$SHELL" "$@"
  else
    command nix "$@"
  fi
}

if [ -n "$SSH_CLIENT" ]; then
  LOCKED="$(busctl --user get-property org.freedesktop.secrets /org/freedesktop/secrets/collection/login org.freedesktop.Secret.Collection Locked 2>/dev/null | awk '{printf "%s", $2}')"

  if "$LOCKED"; then
    printf 'Unlock keyring (enter password for %s): ' "$USER"
    read -s PASS
    echo ""
    printf '%s' "$PASS" | gnome-keyring-daemon --unlock --replace >/dev/null 2>&1
    unset PASS
  fi
fi



if [[ $TERM != "dumb" ]]; then
  eval "$(starship init zsh)"
fi
eval "$(zoxide init zsh )"
