name: release-dotfiles-zsh
on:
  push:
    tags:
      - "v*.*.*"
      - "!v*.*.*-*" # Ignore prerelease tags
  schedule:
    - cron: '3 6 * * 5' # Run weekly on Fridays
jobs:
  release-dotfiles:
    name: release dotfiles
    runs-on: ubuntu-latest
    steps:
      - name: check-last-run
        if: ${{ github.event_name == 'schedule' }}
        run: |-
          LAST_RUN_DATE=$(gh api \
            --jq '.[0].created_at' \
            /repos/${{ github.repository }}/actions/workflows/${{ github.workflow_id }}/runs \
            --paginate \
            -F status=success \
            -F event=schedule \
            --limit 1)

          if ! [ -z "$LAST_RUN_DATE" ]; then
            LAST_RUN_TIMESTAMP=$(date -d "$LAST_RUN_DATE" +%s)
            CURRENT_TIMESTAMP=$(date +%s)
            NINETY_DAYS_IN_SECONDS=$((90 * 24 * 60 * 60))

            if (( CURRENT_TIMESTAMP - LAST_RUN_TIMESTAMP < NINETY_DAYS_IN_SECONDS )); then
              echo "It has been fewer than 90 days. Aborting"
              exit 0
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: generate-token
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: install-nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
      - name: bundle-artifact
        run: |-
          d="$(date -u +%Y-%m-%d)"
          tag="v$(sed -n 's/.*version = "\(.*\)".*/\1/p' flake.nix)"
          version="${tag}-${d}"

          echo "TAG=${tag}" >> "$GITHUB_ENV"
          echo "VERSION=${version}" >> "$GITHUB_ENV"

          for sys in 'x86_64-linux' 'x86_64-darwin' 'aarch64-linux' 'aarch64-darwin'; do
            tar czf "dotfiles-zsh-${version}-${sys}.tar.gz" -C "dotfiles/${sys}" .
          done

          awk 'BEGIN{ c = 0; }/^## /{ c = c + 1; }NR > 2{ if (c <= 1) { print; } }' CHANGELOG.md > RELEASE_NOTES.txt
          cat RELEASE_NOTES.txt

          ls
      - name: tag
        if: ${{ github.event_name != 'push' }}
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: "${{ env.VERSION }}"
          tag_prefix: ""
          append_to_pre_release_tag: ""
          github_token: ${{ steps.generate-token.outputs.token }}
      - name: create-release
        uses: softprops/action-gh-release@v2.3.2
        with:
          body_path: RELEASE_NOTES.txt
          prerelease: ${{ github.event_name != 'push' }}
          files: |-
            README.md
            CHANGELOG.md
            *.tar.gz
          name: "dotfiles-zsh ${{ github.event_name == 'push' && env.TAG || env.VERSION }}"
          token: ${{ steps.generate-token.outputs.token }}
          tag_name: ${{ github.event_name == 'push' && env.TAG || env.VERSION }}
